### ISSUE TITLE
Various errors when launching

### ISSUE THREAD

**Issue by Snakiter** [DanHarasymiw/disteam#1]
Hello.

I am trying to run your code but I'm getting a bunch of errors
![image](https://user-images.githubusercontent.com/30733488/28981636-cea75552-7952-11e7-9630-1915371dc7ca.png).

Are you still maintaining this project ?

Regards.

**Comment by danharasymiw** [comment]
Not really working on this anymore, but I do have a semi working branch on a local computer I can fix and push up. I stopped working on this quite a while ago because its not really possible to search for people by their steam username. Instead you can search by their vanity url for their steam community page. This works for a lot of cases as many people have their username in their community vanity url, lots of people however just have a random number. A semi solution that I had thought of to solve this is if you do find one of the users in the list of people you're given, is to go through their friend list and try and find the person you can't find.

**Comment by danharasymiw** [comment]
Issue now fixed.

**Comment by Snakiter** [comment]
Yes please I'd be interested if you'd have one working build.
